# Specifies where to get the base image and creates a new container for it
FROM node:24

# install C compiler for native node deps
RUN apt-get update && \
    apt-get install -y vim && \
    apt-get install -y software-properties-common build-essential

WORKDIR /home/node/app

COPY package*.json ./

RUN npm ci && \
    ls -al /home/node/app

COPY . .

CMD ["npm", "run", "docs:build-preview", "--", "--host", "0.0.0.0", "--port", "4173"]