version: '3.9'
x-env: &env-vars
  MYSQL_ROOT_PASSWORD: my3qllocal
  MYSQL_DATABASE: sqlermysql
  MYSQL_PORT: 3306
services:
  # MySQL: https://hub.docker.com/_/mysql
  sqler_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: sqler_db
    restart: always
    environment:
      <<: *env-vars
    networks:
      - sqler
  # NodeJS for sqler dialect testing
  sqler_dialect:
    container_name: sqler_dialect
    depends_on:
      - sqler_db
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        <<: *env-vars
    networks:
      - sqler
    ports:
      - 4001:80
    restart: unless-stopped
    environment:
      <<: [ *env-vars ]
    volumes:
      - ./docs:/home/node/app/docs
networks:
  sqler:
    driver: bridge
    name: sqler_net