version: '3.9'
x-env: &env-vars
  MYSQL_ROOT_PASSWORD: my3qllocal
  MYSQL_DATABASE: sqlermysql
  MYSQL_PORT: 3306
x-env-sqler: &env-tokens
  GITHUB_TOKEN: ${GITHUB_TOKEN}
  NPM_TOKEN: ${NPM_TOKEN}
services:
  # MySQL: https://hub.docker.com/_/mysql
  sqler_mdb:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: sqler_mdb
    restart: unless-stopped
    environment:
      <<: *env-vars
    networks:
      - app
    healthcheck:
      # test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", '-p$$MYSQL_ROOT_PASSWORD' ]
      test: out=$$(mysqladmin ping -h localhost -P 3306 -u root --password=$$MYSQL_ROOT_PASSWORD 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
  # NodeJS for sqler dialect testing
  sqler_mdb_dialect:
    container_name: sqler_mdb_dialect
    depends_on:
      - sqler_mdb
    build:
      context: .
      dockerfile: Dockerfile.ci
      args:
        <<: *env-vars
    links:
      - "sqler_mdb:sqler_mdb_database"
    networks:
      - app
    healthcheck:
      test: curl --fail http://localhost:80/healthcheck || exit 1
      timeout: 20s
      retries: 10
    ports:
      - 4001:80
      - 9229:9229
    restart: unless-stopped
    environment:
      <<: [ *env-vars, *env-tokens ]
    volumes:
      - ./docs:/home/node/app/docs
networks:
  app:
    driver: bridge
    name: sqler_mdb_net